import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Disables stylistic rules that would conflict with Prettier. Must stay last.
  prettier,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "coverage/**",
    "next-env.d.ts",
    "src/lib/fonts/files/**",
    // Generated by scripts/sync-public-fonts.mjs — vendored third-party
    // bundles, not code this project maintains.
    "public/**",
    // Generated by `prisma generate`; not code this project maintains.
    "src/generated/**",
  ]),
]);

export default eslintConfig;
