/**
 * The sign-in email itself (M2-T2).
 *
 * Kept separate from delivery (`./mail.ts`) and from the Auth.js wiring
 * (`./config.ts`) because it is the only part a person reads, and it is the
 * part most likely to be edited by someone who is not thinking about OAuth.
 *
 * Three constraints shape the content:
 *
 *   1. **No tracking.** No pixel, no wrapped redirect, no remote image. §9
 *      forbids third-party analytics on builder routes; an email that phones
 *      home the moment it is opened would be the same violation by post.
 *   2. **No resume content, ever.** The transactional provider is allowed to
 *      see an address because it must. It is not allowed to see anything the
 *      user wrote.
 *   3. **Say what the link does and when it stops working.** A magic link
 *      that arrives with no explanation is indistinguishable from a phishing
 *      attempt, which is how people learn to click them without thinking.
 */

import { PRODUCT_NAME } from "@/lib/product";
import type { MailMessage } from "./mail";

export interface MagicLinkParams {
  /** The address the link was requested for. */
  identifier: string;
  /** Auth.js's single-use callback URL. */
  url: string;
  /** When the token stops being accepted. */
  expires: Date;
  /** Clock seam, so the "expires in" phrasing is testable. */
  now?: Date;
}

const HTML_ESCAPES: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&#39;",
};

/**
 * Escapes for HTML text and attribute contexts alike.
 *
 * The URL is generated by Auth.js and the address by the user. Only one of
 * those is trustworthy, and interpolating either into markup unescaped is
 * how an address becomes markup in someone's mail client.
 */
export function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (char) => HTML_ESCAPES[char] ?? char);
}

/** "15 minutes" / "1 hour" / "24 hours" — whichever reads most plainly. */
export function describeExpiry(expires: Date, now: Date = new Date()): string {
  const minutes = Math.max(1, Math.round((expires.getTime() - now.getTime()) / 60_000));
  if (minutes < 90) return `${minutes} minute${minutes === 1 ? "" : "s"}`;
  const hours = Math.round(minutes / 60);
  return `${hours} hour${hours === 1 ? "" : "s"}`;
}

/**
 * Builds the message. `to` is filled in by the caller so this stays a pure
 * function of its inputs and can be snapshot-tested.
 */
export function magicLinkMessage(params: MagicLinkParams): Omit<MailMessage, "to"> {
  const { url, identifier, expires, now = new Date() } = params;
  const host = new URL(url).host;
  const window = describeExpiry(expires, now);

  const text = [
    `Sign in to ${PRODUCT_NAME}`,
    "",
    `Someone asked to sign in to ${host} as ${identifier}. If that was you,`,
    "open this link:",
    "",
    url,
    "",
    `The link works once and expires in ${window}.`,
    "",
    "If it was not you, nothing has happened yet and you can ignore this",
    "message. There is no password on this account to change.",
  ].join("\n");

  // Inline styles only, and no external asset of any kind. Mail clients
  // strip <style> blocks, and a remote image is a tracking pixel whether or
  // not it was meant as one.
  const html = [
    `<div style="font-family:system-ui,-apple-system,Segoe UI,sans-serif;font-size:15px;line-height:1.5;color:#18181b">`,
    `<p style="margin:0 0 16px"><strong>Sign in to ${escapeHtml(PRODUCT_NAME)}</strong></p>`,
    `<p style="margin:0 0 16px">Someone asked to sign in to ${escapeHtml(host)} as ${escapeHtml(identifier)}. If that was you, open this link:</p>`,
    `<p style="margin:0 0 16px"><a href="${escapeHtml(url)}" style="color:#0369a1">Sign in to ${escapeHtml(PRODUCT_NAME)}</a></p>`,
    `<p style="margin:0 0 16px;color:#52525b">The link works once and expires in ${escapeHtml(window)}.</p>`,
    `<p style="margin:0;color:#52525b">If it was not you, nothing has happened yet and you can ignore this message. There is no password on this account to change.</p>`,
    `</div>`,
  ].join("");

  return { subject: `Sign in to ${PRODUCT_NAME}`, text, html };
}
